import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :win_hostname_dns, WinHostnameDnsWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configures the DNS server (see config.exs for documentation on the values)
config :win_hostname_dns, WinHostnameDns.DnsServer,
  port: 53,
  # 3 hours
  expiration_seconds: 60 * 60 * 3

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
